# Generated by Django 3.1.3 on 2020-12-04 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cust_addres',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cust_addres',
            name='street',
            field=models.CharField(max_length=50),
        ),
    ]
