# Generated by Django 3.1.1 on 2020-12-08 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_interface', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data',
        ),
    ]
