# Generated by Django 3.1.1 on 2020-11-24 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_interface', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cust_address',
            new_name='Cust_addres',
        ),
        migrations.RenameModel(
            old_name='Cust_details',
            new_name='Cust_detail',
        ),
        migrations.RenameModel(
            old_name='Cust_lifts',
            new_name='Cust_lift',
        ),
    ]
