# Generated by Django 3.1.1 on 2020-11-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_interface', '0002_auto_20201124_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust_addres',
            name='pincode',
            field=models.IntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name='cust_detail',
            name='phone_no',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cust_lift',
            name='count',
            field=models.IntegerField(max_length=3),
        ),
    ]
