# Generated by Django 3.1.3 on 2020-12-05 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_interface', '0002_auto_20201204_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cust_addres',
            name='user',
        ),
    ]
