# Generated by Django 3.1.1 on 2020-11-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_interface', '0003_auto_20201124_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='customer_interface/images')),
            ],
        ),
        migrations.AlterField(
            model_name='cust_addres',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='cust_detail',
            name='phone_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cust_lift',
            name='count',
            field=models.CharField(max_length=3),
        ),
    ]
