# Generated by Django 3.1.3 on 2020-12-06 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_interface', '0003_remove_cust_addres_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cust_addres',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer_interface.cust_detail'),
            preserve_default=False,
        ),
    ]
