# Generated by Django 3.1.1 on 2020-12-08 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_interface', '0003_auto_20201208_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cust_addres',
            name='username',
        ),
    ]
