# Generated by Django 3.1.1 on 2020-11-28 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer_interface', '0004_auto_20201127_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='cust_detail',
            name='address',
            field=models.CharField(default='x', max_length=100),
        ),
        migrations.AddField(
            model_name='cust_detail',
            name='address_2',
            field=models.CharField(default='x', max_length=100),
        ),
        migrations.AddField(
            model_name='cust_detail',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cust_detail',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cust_detail',
            name='state',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cust_detail',
            name='zip',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
