# Generated by Django 3.1.3 on 2020-12-06 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_interface', '0004_cust_addres_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cust_addres',
            name='username',
        ),
    ]
