# Generated by Django 3.1.3 on 2020-12-06 10:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer_interface', '0005_remove_cust_addres_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='cust_addres',
            name='sername',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer_interface.cust_detail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cust_detail',
            name='Username',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
