# Generated by Django 3.1.3 on 2020-12-06 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_interface', '0006_auto_20201206_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cust_addres',
            old_name='sername',
            new_name='Username',
        ),
    ]
