# Generated by Django 3.1.1 on 2020-11-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_interface', '0007_auto_20201128_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust_detail',
            name='Address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cust_detail',
            name='Address_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cust_detail',
            name='City',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='cust_detail',
            name='Firstname',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='cust_detail',
            name='Lastname',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='cust_detail',
            name='Password',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='cust_detail',
            name='Password_Again',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='cust_detail',
            name='Phone_no',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='cust_detail',
            name='State',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='cust_detail',
            name='Username',
            field=models.EmailField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='cust_detail',
            name='Zip',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='cust_detail',
            name='cust_id',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
