# Generated by Django 3.1.3 on 2020-12-06 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_interface', '0007_auto_20201206_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cust_addres',
            old_name='Username',
            new_name='Cust_detail',
        ),
    ]
