# Generated by Django 3.1.3 on 2020-12-06 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_interface', '0008_auto_20201206_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cust_detail',
            name='Username',
        ),
    ]
