# Generated by Django 3.1.3 on 2020-12-06 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_interface', '0009_remove_cust_detail_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cust_addres',
            name='Cust_detail',
        ),
    ]
