# Generated by Django 3.1.3 on 2020-12-06 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_interface', '0010_remove_cust_addres_cust_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='cust_addres',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='username', to='customer_interface.cust_detail'),
            preserve_default=False,
        ),
    ]
