# Generated by Django 3.1.3 on 2020-12-07 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_interface', '0013_auto_20201206_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust_addres',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Users', to='customer_interface.cust_detail'),
        ),
    ]
